version: "2.1"
services:
  influxdb:
      image: influxdb:latest
      networks:
        - homelab
      ports:
        - '8086:8086'
      volumes:
        - influxdb-storage:/var/lib/influxdb
      environment:
        - INFLUXDB_DB=db0
        - INFLUXDB_ADMIN_USER=influxdbuser
        - INFLUXDB_ADMIN_PASSWORD=influxdbpassword
      logging:
        driver: gelf
        options:
          gelf-address: "udp://localhost:12201" # Logstash UDP input port
          labels: "serviceName=influxdb"
          tag: "influxdb"
      restart: always
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.influxdb.rule=Host(`influxdb.homelab.local`)"
        - "traefik.http.services.influxdb.loadbalancer.server.port=8086"
        - "traefik.http.routers.influxdb.entrypoints=web"
        - "traefik.http.routers.influxdb.middlewares=influxdb-stripprefix"
        - "traefik.http.middlewares.influxdb-stripprefix.stripprefix.prefixes=/influxdb"
        - "serviceName=influxdb"
volumes:
  influxdb-storage:
networks:
  homelab:
    external: true