version: "2.1"
services:
  influxdb:
      image: influxdb:latest
      ports:
        - '8086:8086'
      volumes:
        - influxdb-storage:/var/lib/influxdb
      environment:
        - INFLUXDB_DB=db0
        - INFLUXDB_ADMIN_USER=influxdbuser
        - INFLUXDB_ADMIN_PASSWORD=influxdbpassword
      logging:
        driver: gelf
        options:
          gelf-address: "udp://localhost:12201" # Logstash UDP input port
          tag: "portainer"
      restart: always
volumes:
  influxdb-storage: