---
- name: Uninstall k3s from all nodes
  hosts: k3s_cluster
  become: yes
  tasks:
    - name: Ensure k3s is uninstalled
      shell: /usr/local/bin/k3s-uninstall.sh
      args:
        executable: /bin/bash
      ignore_errors: yes  # Optional: continue if some nodes fail
