---
- name: Ensure Docker network exists
  community.docker.docker_network:
    name: homelab
    state: present
    ipam_config:
      - subnet: '10.7.1.0/24'
      - gateway: '10.7.1.0'
- name: deploy Docker Compose stack - portainer
  community.docker.docker_compose:
    project_src: /home/nick/docker-compose/portainer
    files:
    - docker-compose.yml
#- name: deploy Docker Compose stack - jenkins
#  community.docker.docker_compose:
#    project_src: /home/nick/docker-compose/dockercompose/jenkins
#    files:
#    - docker-compose.yml
#- name: deploy Docker Compose stack - prometheus-grafana
#  community.docker.docker_compose:
#    project_src: /home/nick/docker-compose/dockercompose/prometheus-grafana
#    files:
#    - docker-compose.yml
#- name: deploy Docker Compose stack - pihole
#  community.docker.docker_compose:
#    project_src: /home/nick/docker-compose/dockercompose/pihole
#    files:
#    - docker-compose.yml
- name: deploy Docker Compose stack - elk
  community.docker.docker_compose:
    project_src: /home/nick/docker-compose/elk
    files:
    - docker-compose.yml
#- name: deploy Docker Compose stack - heimdall
#  community.docker.docker_compose:
#    project_src: /home/nick/docker-compose/dockercompose/heimdall
#    files:
#    - docker-compose.yml
- name: deploy Docker Compose stack - jupyter
  community.docker.docker_compose:
    project_src: /home/nick/docker-compose/jupyter
    files:
    - docker-compose.yml
- name: deploy Docker Compose stack - influxdb
  community.docker.docker_compose:
    project_src: /home/nick/docker-compose/influxdb
    files:
    - docker-compose.yml
- name: deploy Docker Compose stack - traefik
  community.docker.docker_compose:
    project_src: /home/nick/docker-compose/traefik
    files:
    - docker-compose.yml

