---
- name: Install common tools
  hosts: all
  become: yes
  become_method: sudo
  become_user: root

  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Upgrade all packages
      ansible.builtin.apt:
        upgrade: dist
        update_cache: yes

    - name: Install packages
      ansible.builtin.apt:
        name:
          - net-tools
          - nano
          - htop
          - python3-pip
          - curl
          - qemu-guest-agent
        state: present

    - name: Ensure qemu-guest-agent is enabled and running
      ansible.builtin.systemd:
        name: qemu-guest-agent
        enabled: yes
        state: started
