---
- name: Install common tools
  hosts: all
  become: yes

  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600
      become: yes  # Explicitly add this

    - name: Upgrade all packages
      ansible.builtin.apt:
        upgrade: dist
        update_cache: yes
      become: yes  # Explicitly add this

    - name: Install packages
      ansible.builtin.apt:
        name:
          - net-tools
          - nano
          - htop
          - python3-pip
          - curl
        state: present
      become: yes  # Explicitly add this
