---
- name: Install K3s Kubernetes Cluster
  hosts: k3s_cluster
  become: yes
  tasks:
    - name: Download K3s installation script
      get_url:
        url: https://get.k3s.io
        dest: /tmp/install-k3s.sh
        mode: '0755'

    - name: Install K3s on Control Plane with Traefik Disabled
      command: sh /tmp/install-k3s.sh --disable traefik
      when: inventory_hostname in groups['k3s_control']
      register: k3s_installation

    - name: Capture the K3s token from Control Plane
      shell: cat /var/lib/rancher/k3s/server/node-token
      when: inventory_hostname in groups['k3s_control']
      register: k3s_token
      changed_when: false

    - name: Install K3s on Worker Nodes with Traefik Disabled
      command: >
        sh /tmp/install-k3s.sh agent --server https://{{ hostvars['control1']['ansible_host'] }}:6443
        --token {{ hostvars['control1']['k3s_token'].stdout }} --disable traefik
      when: inventory_hostname in groups['k3s_workers']
