pipeline {
    agent any
    environment {
        ANSIBLE_HOST_KEY_CHECKING = "False"
    }
    stages {
        stage('Checkout') {
            steps {
                git 'https://github.com/18visions/homelabv2.git'
            }
        }
        stage('List Files') {
            steps {
                sh 'ls -lah'
            }
        }
        stage('Deploy') {
            steps {
                sshagent(['ansible_ssh']) {
                    script {
                        // Run Ansible playbook
                        ansiblePlaybook(
                            playbook: 'JenkinsJobs/ansible_playbooks/install_k3s/install_k3s.yaml',
                            inventory: "JenkinsJobs/ansible_playbooks/install_k3s/hosts.ini",
                            extraVars: [
                                ansible_user: 'nick'
                            ],
                            disableHostKeyChecking: true
                        )
                    }
                }
            }
        }
    }
    post {
        success {
            echo 'Deployment completed successfully.'
        }
        failure {
            echo 'Deployment failed.'
        }
    }
}
