version: "3"

services: 
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.10
    environment: 
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
    networks: 
      - homelab
    mem_limit: 4g
    restart: always

  logstash:
    image: docker.elastic.co/logstash/logstash:7.17.10
    depends_on: 
      - elasticsearch
    ports:
      - 12201:12201/udp
      - 5044:5044 
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf:ro 
    networks:
      - homelab
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.tcp.routers.logstash-beats.rule=Host(`logstash-beats.homelab.local`)"
      - "traefik.tcp.services.logstash-beats.loadbalancer.server.port=5044"
      - "traefik.tcp.routers.logstash-beats.entrypoints=tcp"
      - "traefik.udp.routers.logstash-gelf.rule=Host(`logstash-gelf.homelab.local`)"
      - "traefik.udp.services.logstash-gelf.loadbalancer.server.port=12201"
      - "traefik.udp.routers.logstash-gelf.entrypoints=udp"

  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.10
    depends_on:
      - logstash
    ports: 
      - 5601:5601
    networks: 
      - homelab
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.kibana.rule=Host(`kibana.homelab.local`)"
      - "traefik.http.services.kibana.loadbalancer.server.port=5601"
      - "traefik.http.routers.kibana.entrypoints=web"
      - "traefik.http.routers.kibana.middlewares=kibana-stripprefix"
      - "traefik.http.middlewares.kibana-stripprefix.stripprefix.prefixes=/kibana"

networks:
  homelab:
    external: true