version: "3"

services: 
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.10
    environment: 
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
    networks: 
      - logging-network
    restart: always

  logstash:
    image: docker.elastic.co/logstash/logstash:7.17.10
    depends_on: 
      - elasticsearch
    ports:
      - 12201:12201/udp
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf:ro 
    networks:
      - logging-network
    restart: always

  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.10
    depends_on:
      - logstash
    ports: 
      - 5601:5601
    networks: 
      - logging-network
    restart: always

networks: 
  logging-network:
    driver: bridge